services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OWNER_NUMBER
        sync: false
      - key: PAIRING_CODE
        value: "on"
      - key: SESSION_ID
        sync: false
      - key: PORT
        value: "3000"
